# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  
  # MySQL Cluster dengan 3 node
  (1..3).each do |i|
    config.vm.define "eas-db#{i}" do |node|
      node.vm.hostname = "eas-db#{i}"
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.network "private_network", ip: "192.168.33.1#{i}"

      # Opsional. Edit sesuai dengan nama network adapter di komputer
      node.vm.network "public_network", bridge: "wlp2s0"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = "eas-db#{i}"
        vb.gui = false
        vb.memory = "512"
      end
  
      node.vm.provision "shell", path: "deployMySQL1#{i}.sh", privileged: false
    end
  end

  config.vm.define "eas-proxy2" do |proxy2|
    proxy2.vm.hostname = "eas-proxy2"
    proxy2.vm.box = "bento/ubuntu-16.04"
    proxy2.vm.network "private_network", ip: "192.168.33.10"
    proxy2.vm.network "public_network",  bridge: "wlp2s0"
    
    proxy2.vm.provider "virtualbox" do |vb|
      vb.name = "eas-proxy2"
      vb.gui = false
      vb.memory = "512"
    end

    proxy2.vm.provision "shell", path: "deployProxySQL.sh", privileged: false
  end

end
